name: Gerar JSON EarthWatch Diário

on:
  schedule:
    - cron: '0 8 * * *'  # Executado diariamente às 08:00 UTC
  workflow_dispatch:      # Permite execução manual

jobs:
  gerar-json:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache de dependências
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de geração
        run: |
          for i in {1..3}; do python gerar_json_diario.py > log_processamento.txt 2>&1 && break || sleep 10; done
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit e push do novo JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add 2ps_earthwatch_diario.json
          git commit -m "Atualização automática do JSON EarthWatch - $(date +'%Y-%m-%d')" || echo "Nada novo para commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
