name: Gerar JSON EarthWatch Diário

on:
  schedule:
    - cron: '0 8 * * *'  # Executa diariamente às 08:00 UTC (5h no Brasil)
  workflow_dispatch:     # Permite execução manual

jobs:
  gerar-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache de dependências
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar instalação do OpenCV
        run: python -c "import cv2; print('OpenCV version:', cv2.__version__)"

      - name: Baixar e processar imagem de Cumiana
        run: |
          for i in {1..3}; do python  2ps-earthwatc/gerar_json_diario.py > log_processamento.txt 2>&1 && break || sleep 10; done
        env:
          PYTHONUNBUFFERED: 1

      - name: Gerar arquivo de timestamp simbólico
        run: |
          echo "Última atualização: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > .update_timestamp

      - name: Verificar estado do Git antes do commit
        run: |
          git status
          git remote -v
          git log -1 || echo "Nenhum commit anterior"

      - name: Commit e push do novo JSON e timestamp
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add 2ps-earthwatc/2ps_earthwatch_diario.json .update_timestamp || echo "Nada para adicionar"
          git commit -m "Atualização automática do JSON EarthWatch - $(date +'%Y-%m-%d')" || echo "Nada novo para commit"
          git push || echo "Falha ao fazer push. Verifique permissões."

          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
